### ISSUE TITLE
WEB HOOK

### ISSUE THREAD

**Issue by fathira** [bankopen/layer-cs-cart-plugin#2]
![Screenshot 2022-10-05 at 16-08-58 Open - Asia's First Neobanking Platform for SMEs   Startups](https://user-images.githubusercontent.com/22996973/194080389-0518a8ac-9f91-437b-8267-548cccdddc9c.png)

![live mode](https://user-images.githubusercontent.com/22996973/194080414-ffec7cc3-75c1-4a64-abe4-f6321cc64788.jpg)
hello 
open account live mode  asking webhook url  witch is webhook url?  how to generate webhook url ? please inform (cs-cart version 4.15.1)...... see attachment  
Return URL http://www.xxxxxxx.com/index.php?dispatch=payment_notification.return&payment=layerpayment not supported 
nb: Return URL and webhook url support only seo friendly url (dispatch url not supported)
test mode supported Return URL  https://www.xxxxxx.com/order-landing.html
fathira
also please inform fathira@gmail.com
thanks

**Comment by asif0777** [comment]
@fathira Please contact our pg support on pg-support@bankopen.co
